### ISSUE TITLE
Code release requirement

### ISSUE THREAD

**Issue by lyu-yx** [bochenxie/EISNet#1]
Dear Bochen,

Thanks for your great work! I am wondering when will the code be released?

Best,
Yixuan

**Comment by Candy-Crusher** [comment]
Any updates?

**Comment by bochenxie** [comment]
> Dear Bochen,
> 
> Thanks for your great work! I am wondering when will the code be released?
> 
> Best, Yixuan

Dear Yixuan @lyu-yx,

Thank you for your interest in our work! The source code of this project has been released. For project guidelines and model weights, I'll upload them in the next few days.

Besides, Happy Mid-Autumn Festival!

**Comment by Candy-Crusher** [comment]
![image](https://github.com/user-attachments/assets/bbddcdf7-d3b7-42d7-a14e-503e3e5edf31)
"Since the original papers of EDCNet-S2D, CMX, and CMNeXt do not evaluate these two datasets, we re-implement them based on the source code with a 3-channel voxel grid [15] as event representation."
May I ask if you also use DSEC-Semantic train from scratch in reproducing the three networks EDCNet-S2D, CMX, and CMNeXt?

**Comment by bochenxie** [comment]
> "Since the original papers of EDCNet-S2D, CMX, and CMNeXt do not evaluate these two datasets, we re-implement them based on the source code with a 3-channel voxel grid [15] as event representation." May I ask if you also use DSEC-Semantic train from scratch in reproducing the three networks EDCNet-S2D, CMX, and CMNeXt?

@Candy-Crusher Thank you for your inquiry. Not from scratch. At the training stage, the encoders of these three models are loaded with ImageNet pre-trained weights. As for the decoders, they are randomly initialized.
